### ISSUE TITLE
Remove cypher from advertized list for mod_h2?

### ISSUE THREAD

**Issue by Jan-E** [icing/mod_h2#121]
Is there a method to remove a cipher from the advertized list by mod_h2, but keep it for http/1 support? See https://www.apachelounge.com/viewtopic.php?p=34571#34571 for the backgroundinfo.

**Comment by Jan-E** [comment]
Same question for @tatsuhiro-t : Can I exclude TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA in Nghttp2?

**Comment by icing** [comment]
Jan,

technically this should be possible. Since the serverhello carries both protocol and ciphers and cert info, one could influence the other. 

Currently, mod_ssl has no means to do that, I think. I recommend to take that to the dev mailing list.

**Comment by tatsuhiro-t** [comment]
libnghttp2 itself does not use any ciphersuite.  Our applications (nghttp, nghttpd, and nghttpx) use the pre-defined cipher list.  nghttpx has --ciphers option to change the acceptable list.
Perhaps, it would be a good time to switch to Mozilla's modern compatibility list rather than intermediate one.

**Comment by Jan-E** [comment]
Mozilla's modern compatibility list is restricted to only 4 ciphers on a Windows server with SSLfips = on. And the cipher strength is lower than what I have currently configured on
https://www.ssllabs.com/ssltest/analyze.html?d=fips.sessiondatabase.net

![fips256](https://cloud.githubusercontent.com/assets/1757825/20642804/8099ccae-b419-11e6-8a4e-3df23b68358c.png)

Mozilla modern on that same server scores only 90 out of 100 in the SSLlabs test on Cipher Strength.

![mozilla_modern](https://cloud.githubusercontent.com/assets/1757825/20642789/05daf7ea-b419-11e6-8eab-8772d36f50b2.png)

**Comment by Jan-E** [comment]
The only problem with my current setup is this:

![blacklisted](https://cloud.githubusercontent.com/assets/1757825/20642824/f1f317fc-b419-11e6-9558-83db2b0811ee.png)

Some component in the chain should block blacklisted ciphers over http/2: nghttp2, mod_h2 or mod_ssl. @icing suggested on Apachelounge that mod_sslshould do that.

**Comment by bazzadp** [comment]
Jan, there is nothing in your current set up that is supported by Firefox 47 and is not blacklisted since CBC is blacklisted and your two GCM ciphers are not supported by Firefox.

So even if this change was implemented it wouldn't help you here since you'd effectively have to blacklist all 4 CBC ciphers for HTTP/2 leaving nothing left for it to use.

Therefore you will need to add TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 and accept the less than perfect cipher score (the grade is more important IMHO and going for 100% across the board will just leave you with a site that many browsers still in active use cannot visit). When the ChaCha ciphers get more support (both in server and clients) then you could add those in and possibly reach your 100% again but that could take a while...

**Comment by Jan-E** [comment]
Wouldn't Firefox 47 be smart enough to switch back to HTTP/1.1 if it cannot find a non-blacklisted HTTP/2 cipher? The proof of the pudding is in the eating. So I installed Firefox 47.0 x64 on a Windows 7 x64 machine. Well, it turned out Firefox is smart enough. It reverted to HTTP/1.1 and ECDHE-RSA-AES256-SHA:

![firefox47](https://cloud.githubusercontent.com/assets/1757825/20644565/e657065a-b438-11e6-9814-1db4e36f721f.png)

BTW: I checked that this new install of Firefox actually supports HTTP/2. On https://ie8xp.sessiondatabase.net it chose HTTP/2.0 and ECDHE-RSA-AES128-GCM-SHA256

**Comment by bazzadp** [comment]
So again there is no requirement for the requested functionality since the browser mimics this anyway? Though not sure you can (or should!) depend on browser implemention for this.

I still think you should serve the same cipher suites to both HTTP/1.1 and HTTP/2 and use ordering to avoid blacklisting problems. Ultimately the blacklisted ciphers are cryptographically weaker (hence why blacklisted) so to prefer those blacklisted ciphers over others that are stronger does not make sense for either HTTP/2 or HTTP/1.1. The main issue seems to be that ssllabs and HTTP/2 spec differ over whether AES_128_GCM is stronger or weaker than AES_256_CBC. This has been discussed before ( https://community.qualys.com/thread/14192 ) and that, and the new grading changes seem clear that CBC are weaker (https://blog.qualys.com/ssllabs/2016/11/16/announcing-ssl-labs-grading-changes-for-2017 )

**Comment by icing** [comment]
I agree with @bazzadp  that the same cipher config should be available, regardless if h1 or h2 is negotiated. One protects the resources, not the protocols, right? So, I think the current mod_ssl directives should work fine.

As to what cipher is graded how: it would be nice if all could agree, but that will probably never be stable.

**Comment by Jan-E** [comment]
OK. Since even Firefox 47 does not have problems with my current setup, I'll leave it a it is.

**Comment by Jan-E** [comment]
Recent post https://community.qualys.com/thread/16824-weakinsecure-according-to-current-protocol
One remarkable quote, related to this issue:
>But when CBC cipher is used with TLS 1.0 it is not really secure.
