### ISSUE TITLE
Building with OpenSSL 3.0.0 fails

### ISSUE THREAD

**Issue by Sp1l** [icing/mod_h2#220]
OpenSSL 3.0.0 is released and has deprecated a number of methods. These trip when `-Werror` is used for compilation.

https://github.com/icing/mod_h2/blob/f711e1e68748724cb70c73142311c605517aa14a/mod_http2/Makefile.am#L22

Building on FreeBSD 13.0-p4 with clang 11.0.1

[Build logs](https://brnrd.eu/poudriere/data/130libre-default-openssl/2021-09-09_17h24m51s/logs/errors/ap24-mod_http2-1.15.23.log) showing the failure

```
h2_push.c:477:5: error: 'SHA256_Update' is deprecated [-Werror,-Wdeprecated-declarations]
    SHA256_Update(ctx, s, strlen(s));
    ^
/usr/local/include/openssl/sha.h:74:1: note: 'SHA256_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
^
```

**Comment by icing** [comment]
Thanks for opening this issue. I believe the necessary changes are small.

The httpd team is in the process of shipping a 2.4.49 and keep OpenSSL3 out of that. We do not want to destabilize the current candidate we have. Also, we want to incorporate OpenSSL3 into our CI testing, so that
on the subsequent version we can assure that all modules no longer use deprecated API features.

Let's keep t this open and I make a release here when I have the changes for this module.

**Comment by notroj** [comment]
Are you building from master?  It should have been fixed with c89910f3a8c1f6d87d1491c78850a6b42a42d661

**Comment by icing** [comment]
I brought this nice change by @notroj back from the dead and made a release! https://github.com/icing/mod_h2/releases/tag/v1.15.24

**Comment by notroj** [comment]
Thank you @icing.  1.15.24 built successfully against OpenSSL 3.0.0 for Fedora 36, for the record.

**Comment by nono303** [comment]
...for the record, 1.15.24 built successfully against OpenSSL 3.0.0 for Windows - VC15, VS16 & VS17 ;)

**Comment by icing** [comment]
Thanks all, closing this.
