### ISSUE TITLE
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

### ISSUE THREAD

**Issue by danielvj** [icing/mod_h2#25]
Hi,

Firstly I have to say that I don't know if I am the problem or not. After setting up the server with it valid cert, I get the error(ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY) when I try to visit the web page using Google Chrome.

My httpd.conf is the default file as well as the test.example.org.conf

**Comment by icing** [comment]
Hi Daniel,

I added a "Known Problems" section in the README regarding this. Chrome/Firefox have added security requirements for a site with h2 deployed and that is, currently, their only way of telling you. 

In the sandbox setup, this is expected, as the server certificates are generated on the fly and do not come from some public certificate authority. The tools in sandbox/install/bin like nghttp or curl, will work against the sandbox. nghttp as it does not checks and curl with the '-k' option that disables cert checks.

For using Chrome/Firefox you need a real certificate from an CA accepted by the browsers that matches the name of your server.

**Comment by LPardue** [comment]
Hi Stefan,

We have been doing some experimentation on the sandbox build and have come to a different conclusion. 

The reporting of ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY by the client in our set up is done in response to the server selecting the cipher suite `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`. This cipher suite is part of the HTTP/2 [Black List](http://http2.github.io/http2-spec/index.html#BadCipherSuites), which states: 

>An HTTP/2 implementation MAY treat the negotiation of any of the following cipher suites with TLS 1.2 as a connection error (Section 5.4.1) of type INADEQUATE_SECURITY

The selection of `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` seems to be caused by the configuration parameters `SSLCipherSuite HIGH:!aNULL:!MD5` and `SSLHonorCipherOrder on`. This causes the server to ignore the client preference, which was `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` and respond with a bad suite.

For the sandbox it may be more useful to use the [Mozilla recommended ciphers](https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility). For example, this is what nghttpx and nghttpd use.

**Comment by icing** [comment]
Lucas, thanks for the link. I will change that to the (current) Mozilla Spec in the next release.

**Comment by drpain** [comment]
Though this may be helpful to some, it explains all the SSL settings required for https:
https://community.letsencrypt.org/t/replacing-apache-with-nginx-for-http2-support/12674/23

**Comment by icing** [comment]
Thanks. This looks also good: https://mozilla.github.io/server-side-tls/ssl-config-generator/
