### ISSUE TITLE
suspicious memory usage + cpu hogging behavior

### ISSUE THREAD

**Issue by lkraav** [icing/mod_h2#33]
apache 2.4.12, mod_h2 0.8.0 (same was observed with 0.7.x series), worker mpm

here's what my `htop -u apache` looks like after X days of operation. take note of the following columns: `RES` or `MEM%`, and `CPU%`

![screenshot from 2015-07-15 13-11-51](https://cloud.githubusercontent.com/assets/147228/8696224/400614be-2af3-11e5-935b-c52f3a75174a.png)

1. Three workers each occupy ~1.3GB of non-shared memory each. Is that normal? It does look like the memory usage is capped, because haven't seen this number reach 20% for example over several weeks. This sort of makes me believe I'm not looking at memory leaks, but would like confirmation perhaps that this is the expected amount of RAM needed.

2. One worker starts spinning wheels at some random unidentified point in time. First few days everything is OK, then suddenly it's hogging the CPU. `strace` has proven useless, because this is what I get

```
$ sudo strace -p 15107
Process 15107 attached
futex(0x7f50f5f9f9d0, FUTEX_WAIT, 15143, NULL
^C
```

or

```
$ sudo strace -p 15107
Process 15107 attached
read(5, 
^C
```

Applications still seem to load normally on the frontend, but I've never seen a cpu hogger be a normal state of things. Any advice on how to look into this?

**Comment by icing** [comment]
Hmm, the CPU hogger seems more serious. (If the process memory indeed is capped, it is certainly interesting where all the mem has gone, but otherwise not devastating.)

Is the complete server idle otherwise or are there connections when this happens? How long does a busy time usually last?

One thing that you can do: if you build the server with symbols (-g) then you can attach with gdb to the process, halt it and get a info about where all threads are right now and what is happending on the call
stack of the more interesting ones.

See: https://httpd.apache.org/dev/debugging.html for details.

**Comment by lkraav** [comment]
Bumped to apache-2.4.16. Haven't gotten around to debugging in deeper detail. Will monitor for behavior differences until then.

**Comment by lkraav** [comment]
I've switched to Event MPM and `php-fpm`. This issue can be closed because it does not reproduce on the new configuration and there's no time to chase it further.

**Comment by lkraav** [comment]
I'm still getting apache to 100% cpu usage. Today it happened after 6 days of uptime.

I can't figure out anything meaningful out of `/server-status`

```
Server Version: Apache/2.4.16 (Unix) OpenSSL/1.0.2d mod_wsgi/4.4.9 Python/2.7.9
Server MPM: event
Server Built: Sep 4 2015 23:52:55

Current Time: Friday, 11-Sep-2015 21:13:04 EEST
Restart Time: Friday, 04-Sep-2015 23:56:40 EEST
Parent Server Config. Generation: 1
Parent Server MPM Generation: 0
Server uptime: 6 days 21 hours 16 minutes 24 seconds
Server load: 2.51 2.40 2.40
Total accesses: 267522 - Total Traffic: 2.0 GB
CPU Usage: u19525.3 s73.59 cu0 cs0 - 3.29% CPU load
.45 requests/sec - 3567 B/second - 7.7 kB/request
14 requests currently being processed, 186 idle workers

PID	Connections 	Threads	Async connections
total	accepting	busy	idle	writing	keep-alive	closing
5384	14	yes	14	186	0	0	0
Sum	14	 	14	186	0	0	0

R_______________________________R____________W__________R_______
_______________________KW_____________________K____________W_W__
__W________R_________________W__W_______________K_______________
________........................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
................................................................
........................................
```

**Comment by icing** [comment]
Hmm. This is not really conclusive for HTTP/2 connections, since the scoreboard does not show much details for those, yet. 

What is no longer there are the numerous 'G' workers that freeze in graceful shutdown and who are never reclaimed, leading to worker and memory exhaustion. I assume your memory usage problems are no longer there?

Do you have any idea how many of the 14 connections that `server-status` shows should be there?

I am thinking mod_h2 could allow for better analysis in such cases...any info might help. Thx.

**Comment by lkraav** [comment]
I think the resource exhaustion problem indeed improved, even though moving from `mod_php` to `mod_fcgi` + `php-fpm` helped big. I have not seen "Scoreboard full" exhaustion since the 0.9.x resource tweaks.

In the meanwhile, I disabled apache-related `logrotate` actions. Since the process seems to get stuck spinning on some endless `read`, perhaps it's me rotating some logfiles away from underneath the server.

When the 100% spin happens next time, I will diagnose it for your `/server-status` question.
