### ISSUE TITLE
Protocols directive not being honored with mutliple VirtualHosts

### ISSUE THREAD

**Issue by RossRogers** [icing/mod_h2#67]
I have multiple `VirtualHost`s in one apache configuration with a mutiple domain certificate (à la #59).  I enabled mod_h2 on one and only one `VirtualHost` with the line:

    Protocols h2 http/1.1

All the other `VirtualHost`s are using:

     Protocols http/1.1

If I navigate to the h2-enabled site, Chrome reports that it is using `h2`.  If I navigate to another non-h2 enabled sited, Chrome _still_ reports that it is using h2 and I get the issue that is being fixed and released in issue #59 .  

If I first navigate to a http/1.1 site, it uses 1.1 and the h2-enabled site uses h2.  However, when I refresh the 1.1 page, it goes to h2 again.

This behavior happens with or without the presence of:

    ProtocolsHonorOrder On

( I see that `On` is its default)

**Comment by icing** [comment]
Chrome really does not remember how it connected to a site in the past, it seems. When it has a h2 connection open, and it keeps them open longer than http/1.1 ones, and the certificate matches, it uses that connection.

And you run into #59 (which we will fix in 2.4.18, coming out soonish).

With 2.4.18, your http/1.1 only site will also be served over the h2 connection to the other site - given that the SSL parameters are all the same. If not, httpd will give 421 again. Depending on the feedback on 2.4.18, I probably have to open a bug against chrome then.

And they'll argue that sites with the same cert should all be reachable over the same connection...we'll see.

**Comment by icing** [comment]
And more to the topic of this issue: 
* different protocols settings on virtual hosts that share the very same certificate will not really be supported, even in 2.4.18
* when sites share a certificate, clients will expect the same security and protocol options to apply to all, at least for HTTP/2 clients.
* mod_http2 will therefore make no extra attempts to fix such a mixed configuration, since there is no correct behaviour that will work with browsers, I think.
* if you have a proposal what should happen, let's hear it!
* ProtocolsHonorOrder only has an effect when the connection is started. When the clients wants protocol "x or y" and the server is configured with protocols "y or x", this directive will influence the outcome.

**Comment by RossRogers** [comment]
Sounds good to me.  I was just trying to find a workaround until you guys got to 2.4.18. 

Thanks for speeding up my website and making me look good with mod_h2!
